### ISSUE TITLE
Alternate CSS for dark mode?

### ISSUE THREAD

**Issue by nmpeterson** [ayman/PrettyJSON#15]
This is a super helpful extension, but the colors look bad when using dark mode.

<img width="470" alt="Image" src="https://github.com/user-attachments/assets/030e1410-1a8f-4d6d-9db6-be251898d0bb" />

I think there are a few possible ways to address this:

- Explicitly set the <body> background color to white
- Detect when dark mode is in use and switch the CSS accordingly
- Provide a set of styles that the user can choose from in extension settings
- Provide a way for users to override the default styles

Thanks for your consideration, and for the nifty extension!

**Comment by ayman** [comment]
Thanks @nmpeterson! We can probably do this as an option for the plugin. Got some CSS you like for a dark mode? Else I'll just make something. It's only about [5 classes](https://github.com/ayman/PrettyJSON/blob/master/PrettyJSON/PrettyJSON%20Extension/prettyJSON.css).

**Comment by nmpeterson** [comment]
I took a quick pass at it:

```css
.aiShamurPrettyJSON .aiShamurPrettyString { color: limegreen; }
.aiShamurPrettyJSON .aiShamurPrettyNumber { color: orange; }
.aiShamurPrettyJSON .aiShamurPrettyBoolean { color: dodgerblue; }
.aiShamurPrettyJSON .aiShamurPrettyNull { color: tomato; }
.aiShamurPrettyJSON .aiShamurPrettyKey { color: deeppink; }
```

![Image](https://github.com/user-attachments/assets/345ce2a5-98d0-4437-8316-0aa7960593b2)
